services:
  nginx:
    build:
      context: ./docker/nginx
  
   
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./my-app:/var/www/html # Laravel application directory
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
   
    expose:
      - "9000" # replaced 9001 if there is conflict on this port.
    ports:
      - "8081:9000" # replaced 9001 if there is conflict on this port.
    volumes:
      - ./my-app:/var/www/html # Laravel application directory
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker/mysql
    platform: linux/x86_64
    ports:
      - "3307:3307" # replaced 3307 if there is conflict on this port. usuall value is 3306
    environment:
      - "LANG=C.UTF-8"
      - "MYSQL_ROOT_PASSWORD=root" # replaced password on your desired value
      - "MYSQL_DATABASE=clinic" # replaced database name on your desired value
      - "MYSQL_PASSWORD=root"
    command: --port=3307
  
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql

networks:
  default:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
